# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlineShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnlineShop

  pod 'Firebase/Database'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'Swinject'

  target 'OnlineShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnlineShopUITests' do
    # Pods for testing
  end

end
